### ISSUE TITLE
Additional ideas:

### ISSUE THREAD

**Issue by Otash360** [abus-aikorea/voice-pro#14]
Good evening (relative to my country's time :) ). There's something I don't like. Often, and especially now, when I use your program to dub Russian videos into Uzbek, the voice doesn't sync properly with the video. That is, sometimes the voices are slow, and as a result, the subsequent voices surpass the actual lip movements. If possible, try to fix this.  

How do I think this can be resolved (my opinion):  
You could identify the timing of the voices according to the subtitles and then adjust the speech rate of the TTS-generated voice. For instance, if the TTS-generated voice's duration is shorter than the time the person in the video is speaking, the speech rate should be reduced; if it's longer, it should be increased.  

Adjusting the speech rate does help, but if the videos are long, it makes it harder for people to determine the exact speech rate.

**Comment by abus-aikorea** [comment]
Thank you sincerely for your suggestion. This problem is something we have been contemplating for a long time as well. 
The crux of the issue is that even with the same expression, the length varies by language. Generally, translations into Chinese and Korean tend to be shorter, while English and Spanish are longer. In particular, Russian seems to be very long. 
Therefore, when dubbing Korean into Russian, we might have to read at double speed to match the time sync. As you pointed out, this is very unnatural and difficult to understand. We have tried to detect sentence lengths and automatically adjust the speaking speed, but the results were not good. 
The best method we propose for translation and dubbing is to use LLMs. In other words, we should entrust the translation to models like ChatGPT. We can simply add a request in the prompt to keep the lengths of the original and translated texts as similar as possible. However, running an LLM on a local PC is still challenging. 
The realistic approach we can support is to provide the translations in an editable format. 

Starting from v1.6.7, both Whisper subtitles and translations can be uploaded and edited externally. 
Additionally, we have separated the translation and dubbing processes for this purpose. Now you can modify the translated sentences before starting the dubbing.


![20241124_194033](https://github.com/user-attachments/assets/5df13186-2da0-460d-a4c4-d3d502f923ff)


One more thing~~ 
We have also added dubbing functionality using F5-TTS in the Studio tab, in addition to Edge-TTS. Try dubbing with Celeb Voice. However, please note that F5-TTS only supports English and Chinese. 


![20241124_194115](https://github.com/user-attachments/assets/eec81785-6605-4c62-ab62-db20be9417c7)

**Comment by Otash360** [comment]
Hello, I thought it wasn't that good, but I found a solution that needs improvement using the Chilab program. Of course, I worked with ChatGPT because I am a beginner programmer :). In short, after chatting with it, I realized that there is a small model, and it can remove filler words and make the text more concise. You should try this: [Link](https://chatgpt.com/share/67435db3-0bcc-800c-bfe6-0fe2b8f6901c) . After removing the filler words, I think speeding up the voice will be more effective.

**Comment by Otash360** [comment]
Hello, I thought it's not that good, but I found a solution that should be improved by using developers. Of course, I worked with ChatGPT because I am a beginner programmer :) In short, after chatting with it, I realized that there's a small model, and it can remove filler words and compact the text. You should try it: https://chatgpt.com/share/67435db3-0bcc-800c-bfe6-0fe2b8f6901c
After removing the filler words, I think speeding up the voice will be more effective.
