### ISSUE TITLE
Can you add all features from AICoverGen?

### ISSUE THREAD

**Issue by DartPower** [abus-aikorea/voice-pro#19]
Can you add all features from AICoverGen?
https://github.com/SociallyIneptWeeb/AICoverGen

**Comment by abus-aikorea** [comment]
I also know AICoverGen. I think it's a great project. 
The main features of AICoverGen are implemented through another project of abus-aikorea called aria-coverson. 
Would you like to try it? 
https://github.com/abus-aikorea/aria-coversong

If you have any other questions or need further assistance, feel free to ask! 😊

**Comment by DartPower** [comment]
You have a plans for merging this projects? 😃

**Comment by abus-aikorea** [comment]
Adding the features of AICoverGen to Voice-Pro doesn't seem like a good idea. 
This is because I think Music and Voice are somewhat different. 
However, adding some features of Voice-Pro to Aria-CoverSong is certainly worth considering. 
I would like to hear your thoughts on this. 
What features do you think should be added?

**Comment by DartPower** [comment]
I have a some idea:
Merge all your AI sound projects in one project like "sound-pro" :)
But this is a theoretically only and just a suggestion.
